Homework 3 GPU Processing
PolinaSavelyeva/ImageProcessing pull request #4
Opened 2023-04-11 19:13 UTC by PolinaSavelyeva

2023-04-13 06:49 UTC, gsvgit requested changes

2023-04-13 06:49 UTC, gsvgit commented on src/ImageProcessing/ArguCommands.fs
> +            | InputPath _ -> "path to a file or a directory where the images will be processed from."
А что с маленькой буквы?

2023-04-13 06:49 UTC, gsvgit commented on src/ImageProcessing/GPU.fs
> +    let kernel = applyFilterGPUKernel clContext localWorkSize
Вы такой обёрткой "убили" возможность компилировать ядро один раз.

2023-04-13 06:49 UTC, gsvgit commented on tests/ImageProcessing.Tests/GPU.fs
> +        "GPUTests"
А ещё можно провертять на случайных картинках и фильтрах, что реализация на CPU ведёт себя так же как и на GPU/

2023-04-13 11:58 UTC, PolinaSavelyeva commented on tests/ImageProcessing.Tests/GPU.fs
> +        "GPUTests"
Случайные картинки вроде генерируются, фильтры тоже генерировать?

2023-04-13 11:58 UTC, PolinaSavelyeva commented on tests/ImageProcessing.Tests/GPU.fs
> +        "GPUTests"
Или на цпу проверять через гпу? Не понятно

2023-04-13 12:02 UTC, PolinaSavelyeva commented on src/ImageProcessing/ArguCommands.fs
> +            | InputPath _ -> "path to a file or a directory where the images will be processed from."
А зачем с большой.

2023-04-13 12:46 UTC, gsvgit commented on tests/ImageProcessing.Tests/GPU.fs
> +        "GPUTests"
Да фильтры тоже можно случайные. 

Ща. Кого "через"? Просто проверить, что две реализации ведут себя одинаково. Как с коллекциями когда-то делали.

2023-04-17 05:56 UTC, gsvgit approved these changes

2023-04-17 05:56 UTC, gsvgit commented on src/ImageProcessing/GPU.fs
> +        let queue = clContext.QueueProvider.CreateQueue()
По идее, вот это можно вынести выше, за лямдбу.

2023-05-14 15:12 UTC, merged